const JSONAPIFactory = require('@cardstack/test-support/jsonapi-factory');

let factory = new JSONAPIFactory();

if (process.env.HUB_ENVIRONMENT === 'development') {
  factory.addResource('boards', 'community').withAttributes({
    title: 'Community'
  });

  factory.addResource('categories', 'snowboarding').withAttributes({
    name: 'Snowboarding'
  });

  factory.addResource('articles', '1').withAttributes({
    slug: 'demo',
    title: 'Snow Fever: Ultimate Fun for Snowboarders, Skiers and all Winter Enthusiasts',
    body: {
      'atoms': [],
      'cards': [],
      'markups': [],
      'version': '0.3.1',
      'sections': [
        [1, 'h2', [[0, [], 0, 'Secret vacation location: Enjoy some peace and quiet, have fun and be one with nature.']]],
        [1, 'p', [[0, [], 0, '“I see nothing but the sky above me, the clouds below me, and masses of snow in between… I’m on top of the world!” says Tim Snowfreak, former winner of the Snowboarding in Strange Places World Championship, amazed at his surroundings as if this were his first day in these high, snow-covered mountains.']]],
        [1, 'p', [[0, [], 0, 'The wondrous backdrop of white summits in the still winter air has fascinated sports enthusiasts for years. In fact, even though nobody really knows where this hidden place is to be found, there are people who claim that snowboarding was invented in this very location. Legend says, several decades ago, a particularly inventive man linked a pair of skis together to create a surfboard-like contraption. Combining the ideas of snow and surfing, he basically built a snurfboard that became extremely famous very soon. Within weeks, snurfers all over the world began to manufacture their own snurfing equipment and found their way here to glide down the (until that point) untouched mountains in the snow. There may not have been slopes or lifts or anything but snow, but people truly loved this place. This is where all the craziness allegedly began—in the snow desert that is nowhere to be found.']]],
        [1, 'p', [[0, [], 0, 'Combining the ideas of snow and surfing, he basically built a snurfboard that became extremely famous very soon. Within weeks, snurfers all over the world began to manufacture their own snurfing equipment and found their way here to glide down the (until that point) untouched mountains in the snow.']]],
        [1, 'p', [[0, [], 0, 'There may not have been slopes or lifts or anything but snow, but people truly loved this place. This is where all the craziness allegedly began—in the snow desert that is nowhere to be found.']]],
        [1, 'p', [[0, [], 0, 'Yet, much has changed since then. These days, the hidden mountains offer one or two sort-of-well-prepared slopes, one lonely little hut, and an actual chairlift too! Granted, it is a lift without a safety bar, but you’ve got hands, right? Just find something, anything, to hold on to during the ride and you’ll probably be just fine.']]],
        [1, 'blockquote', [[0, [], 0, '“I see nothing but the sky above me, the clouds below me, and masses of snow in between… I’m on top of the world!”']]],
        [1, 'p', [[0, [], 0, 'The good news is: While this slightly questionable chairlift may not be able to save your life, it does open before sunrise, which allows both snowboarders and skiers (we’re all friends here) to hit the slope early in the morning.']]],
        [1, 'p', [[0, [], 0, 'Plus, there is plenty more fun to be had. These mountains offer a natural toboggan run that leads from the top of the mountain through the woods all the way down to the valley. Be sure to try it out, but it is highly recommended that you wear snow goggles and extremely resilient snow boots; otherwise, you will very likely find yourself drenched, frozen and unable to walk or see for at least two hours after you’ve finally crossed the finish line, preferably in one piece.']]],
        [1, 'p', [[0, [], 0, 'Snow tubing is a fabulous alternative for everyone who has always wanted to see what floating tires are capable of outside their natural habitat. You can even go night skiing or snowboarding, if you don’t mind the lack of light, as the concept of floodlit pistes has, unfortunately, not reached this little neck of the woods just yet. However, riding down the mountain in the moonlight certainly has its charm for night owls who can’t get enough of the pleasures of winter sports. And if all of these options are too adventurous for your taste, this place features a unique hiking trail through the amazingly idyllic winter landscape, along which you may even see some bears.']]],
        [1, 'p', [[0, [], 0, 'As for sleeping arrangements, the mountain’s lonely little hut usually has a couple rooms available. In case it doesn’t, you can always build an igloo. They are actually warmer than you would think. If they weren’t, how would business models like igloo hotels—where, so they claim, you don’t freeze to death while you sleep—be able to survive? But if you don’t like igloos, you can go for a nice mountain cave too, though you may have to share it with some carnivorous animals. And if you’re lucky, you can even find a cave that looks like the ice queen’s palace—enjoy some pretty snow art before bed and feel like Elsa for a day! ']]],
        [1, 'h2', [[0, [], 0, 'The Alps: Enjoy the sun, the drinks, the spa, and maybe do some snowboarding as well.']]],
        [1, 'p', [[0, [], 0, 'As you carve your way through the Alps, there are marvelous attractions to enjoy. The most significant highlights are naturally the slopes themselves. Imagine perfectly prepared pistes you can run down like a pro, framed by the softest and brightest deep powder snow, where both skiers and snowboarders can get their money’s worth and all their dreams fulfilled. Provided that the winter sporting adventure has been scheduled conveniently. Ideally, you pick a week where every normal person has to work and you’re the only lucky genius who gets to play in the snow. Alternatively, if you play your cards right, you may be able to befriend the owner of the ski lifts. Or you get creative in some other way, to ensure that nobody besides you and your friends will stand “in line” when the first cable car opens at 9 a.m. Whichever way you go about it, if you actually manage to secure the entire skiing and snowboarding region for yourself, you’ve done everything right. You’ve made it. You’ve figured out the mystery of skiing in the Alps. Why? Because of one single, extremely crucial fact: There will be no skiers standing or lying around the slopes, because they thought they could ski without actually knowing how to ski. And there will be no excruciatingly annoying snowboarders either, who are sitting around in a row in the middle of the slope—the most appropriate place imaginable—because they’re too lazy to get back up and keep doing what they came here to do.']]],
        [1, 'p', [[0, [], 0, 'But there is another attraction unique to the Alps, which makes the experience of doing winter sports in the midst of incapable skiers and inconsiderate snowboarders slightly more bearable, if not actually fun. In fact, it provides a great exit strategy—quite literally. It’s made of wood, it has a roof, and it serves drinks. It’s called a ski hut. Or a mountain hut. Or simply hut. Sometimes a cabin.']]],
        [1, 'p', [[0, [], 0, 'Really, you can call it whatever you like. The point is that many huts on the mountains offer fantastic sun terraces, which are a godsend once the temperatures rise a bit. When the winter starts turning into spring, you no longer have to stop by a hut just to keep your feet from turning into ice (by the way, if you press them up against the tiled stove, they will burn). You can actually stop by the hut for fun! Sit down outside in the warmth, wearing your snow boots combined with sunglasses rather than snow goggles, and enjoy the scenery, as the amazing blanket of white reflects the glittering sunlight.']]],
        [1, 'p', [[0, [], 0, 'You should know, however, that there is absolutely no way you will get back on the slopes once you have sat down on one of those mountaintop terraces. Especially once music starts playing and you feel like you have found the one place in the world where you want to live forever. Or until you eventually turn into the Iceman, also known around the world as “the frozen mummy”.']]],
        [1, 'p', [[0, [], 0, 'Though it may be counterintuitive—sometimes, between hut visits, it can be fun to actually get on the board and ride down the slopes too. At least until you hit the next hut, which is typically about 50 meters away. Now, here is an important piece of information: You’re not really supposed to ski or snowboard after you have had a schnapps (or ten); there are huts that offer to bring you back to your hotel by snowcat if you’ve drunk your way through the entire bar by order of après-ski. By the way, as a side note: The huts serve food as well. Mostly apple strudel and schnitzel and fries. If you’re lucky, they even have something nutritious too—like sausages.']]],
        [1, 'p', [[0, [], 0, 'At least as essential as the Alpine sun terraces, après ski and, for some people, the skiing / snowboarding part of the holiday, is the wellness oasis awaiting tourists at every single hotel. So, once you’ve made it back down to the valley, make sure you put on your bathrobe, slippers, and relax for a little while before you go to dinner and fall asleep on the table.']]],
        [1, 'h2', [[0, [], 0, 'North Pole: If it’s still there by the time you arrive, you are welcome to stay!']]],
        [1, 'p', [[0, [], 0, 'This place is like Disneyworld for snow lovers. Being an island of pure fun, it offers adventures for winter fans in every shape and form. There are fun parks everywhere, featuring obstacles, jumps, bumps, turns and kickers for all skill levels, from beginners to pseudo-pros to actual athletes. And off-piste in the powder, you can make your freestyle dreams come true!']]],
        [1, 'p', [[0, [], 0, 'Plus, there are snowboard coasters, snowboard ghost trains, snowboard tunnels, slalom courses, racetracks, half pipes and even some loops! Yes, they have indeed managed to build a loop for snowboarders; and not just any loop, but a double loop and a triple loop. It may be good to mention that, so far, nobody has felt the desire to try it out, as it looks slightly lethal, but it’s there.']]],
        [1, 'p', [[0, [], 0, 'So you’re welcome to be the first to hit the loop! You’ll definitely have a ton of fun showing off in front of everyone who’s too chicken to try. There’s a photo point too, which will gladly take a picture of your success (or lack thereof) and post it immediately on all social media channels with your name and an appropriate hashtag attached.']]],
        [1, 'p', [[0, [], 0, 'For snow enthusiasts with less masochistic tendencies, this place offers the fabulous alternative option of sledding or, for car freaks, riding on a snowcat. When you ask very very nicely, a driver may let you sit on the passenger seat and help him prepare the slopes for the next day, which is a delightful experience you will never forget. “Helping prepare the slopes you get to carve down in the morning is something I can only recommend to anyone who is curious about snow, snowboarding and everything related to it”, says Sara Boarding, a 27-year-old snowboarder who holidays here every season. ']]],
        [1, 'p', [[0, [], 0, 'Of course, this unique vacationing spot has even more to offer than adrenaline pumps and mountain tractors. It boasts the most spectacular slopes known to man: Endlessly wide and endlessly long runs, which are prepared right in front of you as you carve your way downwards, ensuring that the snow is always in pristine condition. Furthermore, the lifts have all the perks you can imagine: heated seats, champagne, red carpet, orchestra… You’ll never want to leave!']]],
        [1, 'p', [[0, [], 0, 'Once you’re tired of all the snowboarding, skiing, snowcat driving, looping and fun parks, you’re welcome to leave the action behind and calm down a little bit further outside the excitement-focused center of the North Pole. Take a walk through the valley, past the ice, through the snow, as you watch penguins and polar bears fight it out for dominance over who gets which of the poles. Walk underneath snow-covered trees, past frozen lakes, through the perfect quietude of this untouched natural miracle—while you’re ideally holding the hand of your sweetheart, as this is romance at its finest. And since the place is shrinking away, there’s not much danger of you getting lost; unless you end up on an ice shell that carries you off, but that’s highly unlikely.']]],
        [1, 'p', [[0, [], 0, 'After such a memorable vacation, it is always nice to think of the poor people whom you left behind before you leave this magical island. That is why the whole village is filled with numerous tourist shops with lovely products on display, most of which you can purchase. Take a stroll through the main shopping street and choose between the countless, extremely tasteful and not at all tacky souvenirs like wooden figurines or plates with embroideries. Alternatively, you could bring some cheese you’ve made yourself in the course of a “This is how we make cheese”-tour through a dairy, or toys that are supposedly made by elves. And for a personal note, you can take advantage of the many photo points around this all-year skiing and snowboarding area to take the joy of snowboarding back home with you.']]]
      ]
    }
  }).withRelated('category', { type: 'categories', id: 'snowboarding' })
    .withRelated('theme', { type: 'themes', id: 'sharp' });
}

module.exports = factory.getModels();
